[workspace]
authors = []
channels = ["conda-forge"]
name = "workshop-csdms2025-exercises"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
preview = "myst start"
render = "myst build --html"

[dependencies]
mystmd = ">=1.3.26,<2"
